#!/bin/sh

# intro
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Welcome to Privoxy Installation!"
echo "      - Hiratechi"
sleep 3
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Stopping your Squid..."
service squid stop
sleep 1
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Stopping your Squid... OK!"
sleep 1
clear

# installation
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Starting to Install Privoxy..."
echo ""
apt-get install privoxy
echo 1 > /etc/privoxy/config
cat > /etc/privoxy/config <<-END
user-manual /usr/share/doc/privoxy/user-manual
confdir /etc/privoxy
logdir /var/log/privoxy
filterfile default.filter
logfile logfile
listen-address 0.0.0.0:3128
listen-address [::1]:3128
listen-address 0.0.0.0:8888
listen-address [::1]:8888
listen-address 0.0.0.0:8000
listen-address [::1]:8000
listen-address 0.0.0.0:8080
listen-address [::1]:8080
toggle 1
enable-remote-toggle 0
enable-remote-http-toggle 0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 1
forwarded-connect-retries 1
accept-intercepted-requests 1
allow-cgi-request-crunching 1
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
END
clear

# outro
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Privoxy has been successfully installed!"
sleep 2
clear

# finalization
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Rebooting your server in 5"
echo "Don't touch anything...!"
echo "(If your squid do not start after reboot type service squid restart)"
sleep 1
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Rebooting your server in 4"
echo "Don't touch anything...!"
echo "(If your squid do not start after reboot type service squid restart)"
sleep 1
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Rebooting your server in 3"
echo "Don't touch anything...!"
echo "(If your squid do not start after reboot type service squid restart)"
sleep 1
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Rebooting your server in 2"
echo "Don't touch anything...!"
echo "(If your squid do not start after reboot type service squid restart)"
sleep 1
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "Rebooting your server in 1"
echo "Don't touch anything...!"
echo "(If your squid do not start after reboot type service squid restart)"
sleep 1
clear
echo "=======================PRIVOXY SETUP======================="
echo ""
echo "BYE!"
sleep 1
reboot
